pipeline {
    agent any

    tools {
        jdk 'JDK21'
    }

    stages {

        stage('Check Java') {
            steps {
                sh '''
                    echo "JAVA_HOME=$JAVA_HOME"
                    which java
                    java -version
                    which javac
                    javac -version
                    which mvn
                    mvn -version
                '''
            }
        }

        stage('Build') {
            steps {
                dir('app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('app') {
                    sh 'mvn test'
                }
            }
        }

        stage('List Artifacts') {
            steps {
                sh 'find app/target -type f'
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'app/target/*.jar',
                                 fingerprint: true
            }
        }
    }
}
